mizukis_cafe/urls.py
from django.urls import path

from . import views

app_name = 'mizukis_cafe'
urlpatterns = [
  path('', views.index, name='index'),
  path('add_beans', views.add_beans, name='add_beans'),
  path('modify_db', views.modify_db, name='modify_db'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mizukis_cafe/', include('mizukis_cafe.urls')),
]

mizukis_cafe/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.

class Beans(models.Model):
  name = models.CharField(max_length=100)
  pub_date = models.DateTimeField(auto_now_add=True)
  rating = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(10)], default=0)

  def __str__(self):
    return self.name

mizukis_cafe/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse

from .models import Beans

# Create your views here.
def index(request):
  all_beans = Beans.objects.all()
  return render(request, 'mizukis_cafe/index.html', {'beans':all_beans})


def add_beans(request):
  return render(request, 'mizukis_cafe/add_beans.html')


def modify_db(request):
  return redirect(reverse('mizukis_cafe:index'))

mizukis_cafe/templates/mizukis_cafe/add_beans.html
<form action={% url 'mizukis_cafe:modify_db' %} method="POST">
  {% csrf_token %}
  <label for="name">Beans name:</label>
  <input type="text" name="name" id="name">
  <label for="rating">Rate:</label>
  <input type="number" step="0.5">
  <input type="submit" value="Submit">
</form>

mizukis_cafe/templates/mizukis_cafe/index.html
<ul>
{% for i in beans %}
  <li>{{ i.name }}</li>
{% endfor %}
</ul>
<a href="{% url 'mizukis_cafe:add_beans' %}">Click</a>